name: m1

on: [push, pull_request]

env:
  BOINC_DIR: ./boinc

jobs:
  build:
    runs-on: macos-26

    name: >-
      macOS 15

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Print gcc version
        run: |
          uname -a
          CURL_CA_BUNDLE=/etc/ssl/cert.pem curl -v https://asteroidsathome.net
