name: m1

on: [push, pull_request]

env:
  BOINC_DIR: ./boinc

jobs:
  build:
    runs-on: macos-26

    name: >-
      macOS 14

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Print gcc version
        run: |
          uname -a
          openssl s_client -connect asteroidsathome.net:443 -servername asteroidsathome.net -showcerts
