name: m1

on: [push, pull_request]

env:
  BOINC_DIR: ./boinc

jobs:
  build:
    runs-on: macos-26

    name: >-
      macOS 14

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Print gcc version
        run: |
          uname -a
          ls -l /etc/ssl/
          ls -l /opt/homebrew/etc/openssl@3
          curl -v
          /opt/homebrew/bin/openssl version -a
          openssl s_client -connect asteroidsathome.net:443 -servername asteroidsathome.net -showcerts -verify_return_error -CAfile /opt/homebrew/etc/ca-certificates/cert.pem
          openssl s_client -connect einsteinathome.org:443 -servername einsteinathome.org -showcerts -verify_return_error -CAfile /opt/homebrew/etc/ca-certificates/cert.pem
          openssl s_client -connect primegrid.com:443 -servername primegrid.com -showcerts -verify_return_error -CAfile /opt/homebrew/etc/ca-certificates/cert.pem
